#feign:
#    client:
#        config:
#            default:
#                connectTimeout: 5000
#                readTimeout: 5000
#                loggerLevel: basic

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
